services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=false
    # expose app on connectors via Forge override file

networks:
  traefik_proxy:
    external: true


